[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "22.20.0"
  NPM_FLAGS = "--legacy-peer-deps"

# Headers para optimización de cache y seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers específicos para archivos estáticos
[[headers]]
  for = "/static/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript"

[[headers]]
  for = "/static/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/css"

[[headers]]
  for = "/static/media/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers para manifest.json
[[headers]]
  for = "/manifest.json"
  [headers.values]
     Content-Type = "application/manifest+json"
     Cache-Control = "public, max-age=3600"

# Headers para archivos HTML (asegurar que no se sirvan como JS/CSS)
[[headers]]
  for = "/*.js"
  [headers.values]
     Content-Type = "application/javascript"
     Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
     Content-Type = "text/css"
     Cache-Control = "public, max-age=31536000, immutable"

# Headers para service worker
[[headers]]
  for = "/sw.js"
  [headers.values]
     Content-Type = "application/javascript"
     Cache-Control = "no-cache"

# Redirecciones SPA - debe estar al final
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200