[build]
   command = "npm install --legacy-peer-deps && npm run build"
   publish = "build"
   ignore = "/bin/false"

[build.environment]
   NODE_VERSION = "20"
   NPM_FLAGS = "--legacy-peer-deps"
   NODE_OPTIONS = "--max_old_space_size=4096"

# Security headers for all pages
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(self)"

# Force proper MIME types for static files (must be before general headers and SPA fallback)
[[headers]]
  for = "/static/js/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript; charset=utf-8"
    X-Content-Type-Options = "nosniff"

# Force proper MIME types for admin static files (IMPORTANT: Before SPA fallback)
[[headers]]
  for = "/admin/static/js/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript; charset=utf-8"
    X-Content-Type-Options = "nosniff"

# Force proper MIME types for admin dynamic chunks (IMPORTANT: Before SPA fallback)
[[headers]]
  for = "/admin/static/js/*.chunk.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript; charset=utf-8"
    X-Content-Type-Options = "nosniff"

# Force proper MIME types for dynamic chunks (IMPORTANT: Before SPA fallback)
[[headers]]
  for = "/static/js/*.chunk.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript; charset=utf-8"
    X-Content-Type-Options = "nosniff"


[[headers]]
  for = "/static/css/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/css; charset=utf-8"
    X-Content-Type-Options = "nosniff"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

# Specific headers for critical files
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Type = "application/manifest+json; charset=utf-8"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "image/x-icon"
    X-Content-Type-Options = "nosniff"

# Security headers for HTML pages
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"


# Environment variables
[context.production.environment]
  REACT_APP_API_URL = "https://transyncbackend-production.up.railway.app"
  REACT_APP_WS_URL = "wss://transyncbackend-production.up.railway.app"
  REACT_APP_NAME = "TransSync"
  REACT_APP_VERSION = "1.1.0"
  REACT_APP_DEBUG_MODE = "false"
  REACT_APP_DEFAULT_COUNTRY = "co"

# Additional headers for problematic chunks with hashes
[[headers]]
  for = "/static/js/*.chunk.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript; charset=utf-8"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/admin/static/js/*.chunk.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript; charset=utf-8"
    X-Content-Type-Options = "nosniff"

# Headers for all JavaScript files
[[headers]]
  for = "/static/js/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript; charset=utf-8"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/admin/static/js/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript; charset=utf-8"
    X-Content-Type-Options = "nosniff"
